In [1]:
SQL_SOURCE = 'https://fb55.carto.com/api/v2/sql?q=SELECT'
import urllib2
import urllib
import StringIO
import ast
import pandas as pd

def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urllib.urlencode({'format': format, 'q': query})
    try:
        response = urllib2.urlopen(source, data)
    except urllib2.HTTPError, e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [2]:
test = '''
SELECT *
FROM citibike
'''

In [3]:
data = pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

In [116]:
data.columns

Index([u'the_geom', u'start_station_name', u'the_geom_webmercator', u'field_1',
       u'start_station_longitude', u'tripduration', u'starttime', u'stoptime',
       u'start_station_id', u'cartodb_id', u'start_station_latitude',
       u'end_station_id', u'end_station_name', u'end_station_latitude',
       u'end_station_longitude', u'bikeid', u'usertype', u'birth_year',
       u'gender'],
      dtype='object')

### task 1

In [129]:
# Sort data by start_station_id, tripduration
# - Only checking trips with duration <= 3 hours

question1_1 = '''
SELECT *
FROM citibike
where tripduration <= 10800
order by tripduration, start_station_id 
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_1)), sep=',')

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,Laight St & Hudson St,NaN,19295,-74.007718,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,19243,40.721854,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970.0,1
1,NaN,Mott St & Prince St,NaN,8347,-73.994800,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,8284,40.723180,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982.0,1
2,NaN,Division St & Bowery,NaN,14163,-73.997047,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,14117,40.714131,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990.0,1
3,NaN,E 6 St & Avenue B,NaN,3178,-73.981854,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,3110,40.724537,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985.0,1
4,NaN,W 31 St & 7 Ave,NaN,7865,-73.991600,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,7798,40.749156,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986.0,1
5,NaN,E 5 St & Avenue C,NaN,45697,-73.979955,60,2015-02-07 21:40:00+00,2015-02-07 21:41:00+00,393,45697,40.722992,393,E 5 St & Avenue C,40.722992,-73.979955,21524,Subscriber,1981.0,1
6,NaN,E 10 St & Avenue A,NaN,38868,-73.981420,60,2015-02-06 20:40:00+00,2015-02-06 20:41:00+00,445,38842,40.727408,445,E 10 St & Avenue A,40.727408,-73.981420,16051,Subscriber,1987.0,1
7,NaN,W 20 St & 8 Ave,NaN,33793,-74.000040,60,2015-02-06 11:38:00+00,2015-02-06 11:39:00+00,470,33759,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,17448,Subscriber,1979.0,1
8,NaN,Grand St & Havemeyer St,NaN,11165,-73.956981,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,11104,40.712868,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980.0,1
9,NaN,5 Ave & E 29 St,NaN,7364,-73.986831,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,7299,40.745168,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956.0,1
10,NaN,W 29 St & 9 Ave,NaN,13533,-73.998393,60,2015-02-04 07:52:00+00,2015-02-04 07:53:00+00,512,13482,40.750073,512,W 29 St & 9 Ave,40.750073,-73.998393,21627,Subscriber,1960.0,2
11,NaN,8 Ave & W 31 St,NaN,13098,-73.994811,60,2015-02-04 06:54:00+00,2015-02-04 06:55:00+00,521,13043,40.750450,521,8 Ave & W 31 St,40.750450,-73.994811,14788,Subscriber,1971.0,1
12,NaN,W 38 St & 8 Ave,NaN,21463,-73.991382,60,2015-02-04 22:38:00+00,2015-02-04 22:39:00+00,523,21407,40.754666,523,W 38 St & 8 Ave,40.754666,-73.991382,16148,Subscriber,1980.0,1
13,NaN,Catherine St & Monroe St,NaN,24446,-73.996826,60,2015-02-05 09:32:00+00,2015-02-05 09:33:00+00,2009,24408,40.711174,2009,Catherine St & Monroe St,40.711174,-73.996826,18581,Subscriber,1983.0,1
14,NaN,E 11 St & 2 Ave,NaN,11714,-73.986724,61,2015-02-03 19:01:00+00,2015-02-03 19:02:00+00,237,11653,40.730473,237,E 11 St & 2 Ave,40.730473,-73.986724,16900,Subscriber,1980.0,1
15,NaN,Mott St & Prince St,NaN,2639,-73.994800,61,2015-02-01 13:39:00+00,2015-02-01 13:40:00+00,251,2570,40.723180,251,Mott St & Prince St,40.723180,-73.994800,20381,Subscriber,1900.0,1
16,NaN,Bayard St & Baxter St,NaN,5781,-73.999744,61,2015-02-01 19:16:00+00,2015-02-01 19:17:00+00,355,5715,40.716021,355,Bayard St & Baxter St,40.716021,-73.999744,15079,Subscriber,1950.0,2
17,NaN,W 26 St & 10 Ave,NaN,918,-74.002950,61,2015-02-01 10:26:00+00,2015-02-01 10:27:00+00,388,850,40.749718,388,W 26 St & 10 Ave,40.749718,-74.002950,15192,Subscriber,1983.0,1
18,NaN,Suffolk St & Stanton St,NaN,7618,-73.985180,61,2015-02-02 18:51:00+00,2015-02-02 18:52:00+00,410,7551,40.720664,410,Suffolk St & Stanton St,40.720664,-73.985180,15131,Subscriber,1984.0,1
19,NaN,Broadway & W 24 St,NaN,10683,-73.989151,61,2015-02-03 17:11:00+00,2015-02-03 17:12:00+00,444,10622,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,19496,Subscriber,1986.0,1
20,NaN,E 20 St & 2 Ave,NaN,6924,-73.982050,61,2015-02-02 10:05:00+00,2015-02-02 10:06:00+00,461,6858,40.735877,461,E 20 St & 2 Ave,40.735877,-73.982050,15005,Subscriber,1993.0,2
21,NaN,E 24 St & Park Ave S,NaN,6999,-73.986022,61,2015-02-02 11:22:00+00,2015-02-02 11:23:00+00,491,6934,40.740964,491,E 24 St & Park Ave S,40.740964,-73.986022,17141,Subscriber,1970.0,1
22,NaN,Pershing Square South,NaN,9022,-73.977910,61,2015-02-03 10:02:00+00,2015-02-03 10:03:00+00,517,8962,40.751581,517,Pershing Square South,40.751581,-73.977910,19406,Subscriber,1976.0,1
23,NaN,Forsyth St & Broome St,NaN,26953,-73.992663,61,2015-02-05 15:34:00+00,2015-02-05 15:35:00+00,531,26912,40.718939,531,Forsyth St & Broome St,40.718939,-73.992663,16247,Subscriber,1964.0,2
24,NaN,MacDougal St & Prince St,NaN,30206,-74.002971,62,2015-02-05 20:25:00+00,2015-02-05 20:26:00+00,128,30162,40.727103,128,MacDougal St & Prince St,40.727103,-74.002971,17860,Subscriber,1980.0,1
25,NaN,LaGuardia Pl & W 3 St,NaN,4570,-73.998102,62,2015-02-01 16:52:00+00,2015-02-01 16:53:00+00,161,4501,40.729170,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,20593,Subscriber,1987.0,1
26,NaN,W 4 St & 7 Ave S,NaN,7201,-74.002939,62,2015-02-02 14:28:00+00,2015-02-02 14:29:00+00,380,7135,40.734011,380,W 4 St & 7 Ave S,40.734011,-74.002939,16863,Subscriber,1967.0,1
27,NaN,E 9 St & Avenue C,NaN,12980,-73.977688,62,2015-02-04 06:29:00+00,2015-02-04 06:30:00+00,394,12922,40.725213,394,E 9 St & Avenue C,40.725213,-73.977688,16107,Subscriber,1979.0,1
28,NaN,W 21 St & 6 Ave,NaN,36216,-73.994156,62,2015-02-06 16:54:00+00,2015-02-06 16:55:00+00,435,36187,40.741740,435,W 21 St & 6 Ave,40.741740,-73.994156,21649,Subscriber,1961.0,1
29,NaN,E 20 St & 2 Ave,NaN,8213,-73.982050,62,2015-02-03 07:35:00+00,2015-02-03 07:36:00+00,461,8146,40.735877,461,E 20 St & 2 Ave,40.735877,-73.982050,17006,Subscriber,1988.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46121,NaN,E 17 St & Broadway,NaN,43083,-73.990093,6785,2015-02-07 15:42:00+00,2015-02-07 17:35:00+00,497,43075,40.737050,268,Howard St & Centre St,40.719105,-73.999733,19050,Customer,NaN,0
46122,NaN,LaGuardia Pl & W 3 St,NaN,7879,-73.998102,6990,2015-02-02 21:55:00+00,2015-02-02 23:52:00+00,161,7812,40.729170,147,Greenwich St & Warren St,40.715422,-74.011220,18742,Subscriber,1969.0,1
46123,NaN,E 52 St & 2 Ave,NaN,43961,-73.967416,7064,2015-02-07 17:09:00+00,2015-02-07 19:07:00+00,441,43954,40.756014,168,W 18 St & 6 Ave,40.739713,-73.994564,19830,Subscriber,1989.0,2
46124,NaN,E 11 St & 1 Ave,NaN,7158,-73.984267,7105,2015-02-02 13:41:00+00,2015-02-02 15:40:00+00,326,7092,40.729538,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,16802,Subscriber,1969.0,1
46125,NaN,Lafayette St & Jersey St,NaN,29895,-73.995653,7165,2015-02-05 19:36:00+00,2015-02-05 21:36:00+00,250,29852,40.724561,511,E 14 St & Avenue B,40.729387,-73.977724,16468,Subscriber,1986.0,1
46126,NaN,South End Ave & Liberty St,NaN,1576,-74.015756,7225,2015-02-01 11:46:00+00,2015-02-01 13:47:00+00,3002,1506,40.711512,499,Broadway & W 60 St,40.769155,-73.981918,21202,Customer,NaN,0
46127,NaN,Broadway & W 55 St,NaN,41914,-73.981923,7464,2015-02-07 13:30:00+00,2015-02-07 15:34:00+00,468,41904,40.765265,468,Broadway & W 55 St,40.765265,-73.981923,15214,Customer,NaN,0
46128,NaN,West Thames St,NaN,3485,-74.017134,7649,2015-02-01 15:03:00+00,2015-02-01 17:10:00+00,363,3417,40.708347,426,West St & Chambers St,40.717548,-74.013221,18074,Subscriber,1983.0,1
46129,NaN,Henry St & Grand St,NaN,758,-73.981346,7739,2015-02-01 09:58:00+00,2015-02-01 12:07:00+00,502,689,40.714215,293,Lafayette St & E 8 St,40.730287,-73.990765,17212,Subscriber,1966.0,1
46130,NaN,E 20 St & FDR Drive,NaN,376,-73.975739,7903,2015-02-01 08:00:00+00,2015-02-01 10:12:00+00,487,308,40.733143,331,Pike St & Monroe St,40.711731,-73.991930,20860,Subscriber,1991.0,1
46131,NaN,Reade St & Broadway,NaN,12288,-74.005628,7990,2015-02-03 20:56:00+00,2015-02-03 23:10:00+00,330,12229,40.714505,386,Centre St & Worth St,40.714948,-74.002345,19732,Subscriber,1977.0,2
46132,NaN,Bialystoker Pl & Delancey St,NaN,42883,-73.982612,8002,2015-02-07 15:19:00+00,2015-02-07 17:32:00+00,356,42874,40.716226,326,E 11 St & 1 Ave,40.729538,-73.984267,20201,Subscriber,1987.0,1
46133,NaN,Pershing Square North,NaN,34751,-73.977706,8254,2015-02-06 14:19:00+00,2015-02-06 16:37:00+00,519,34720,40.751873,501,FDR Drive & E 35 St,40.744219,-73.971212,21535,Subscriber,1950.0,2
46134,NaN,Barclay St & Church St,NaN,7553,-74.010202,8292,2015-02-02 18:29:00+00,2015-02-02 20:47:00+00,417,7486,40.712912,306,Cliff St & Fulton St,40.708235,-74.005301,14711,Subscriber,1972.0,1
46135,NaN,Washington Ave & Park Ave,NaN,9053,-73.967510,8362,2015-02-03 10:10:00+00,2015-02-03 12:30:00+00,313,8992,40.696102,348,W Broadway & Spring St,40.724910,-74.001547,17690,Subscriber,1971.0,2
46136,NaN,Barclay St & Church St,NaN,444,-74.010202,8376,2015-02-01 08:32:00+00,2015-02-01 10:52:00+00,417,376,40.712912,355,Bayard St & Baxter St,40.716021,-73.999744,16292,Subscriber,1950.0,2
46137,NaN,E 12 St & 3 Ave,NaN,21425,-73.988900,8470,2015-02-04 22:31:00+00,2015-02-05 00:52:00+00,483,21369,40.732233,311,Norfolk St & Broome St,40.717227,-73.988021,20201,Subscriber,1987.0,1
46138,NaN,Broadway & W 24 St,NaN,39836,-73.989151,8548,2015-02-07 07:47:00+00,2015-02-07 10:10:00+00,444,39817,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,15620,Customer,NaN,0
46139,NaN,Broadway & W 24 St,NaN,39830,-73.989151,8705,2015-02-07 07:45:00+00,2015-02-07 10:10:00+00,444,39811,40.742354,444,Broadway & W 24 St,40.742354,-73.989151,16131,Customer,NaN,0
46140,NaN,E 11 St & 1 Ave,NaN,21495,-73.984267,9075,2015-02-04 22:46:00+00,2015-02-05 01:17:00+00,326,21438,40.729538,410,Suffolk St & Stanton St,40.720664,-73.985180,16119,Subscriber,1993.0,1
46141,NaN,DeKalb Ave & Hudson Ave,NaN,11871,-73.981013,9373,2015-02-03 19:25:00+00,2015-02-03 22:01:00+00,324,11810,40.689888,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,15018,Subscriber,1968.0,1
46142,NaN,Broadway & W 60 St,NaN,7139,-73.981918,9556,2015-02-02 13:25:00+00,2015-02-02 16:05:00+00,499,7073,40.769155,499,Broadway & W 60 St,40.769155,-73.981918,14802,Subscriber,1940.0,1
46143,NaN,Broadway & E 22 St,NaN,19952,-73.989551,9572,2015-02-04 19:09:00+00,2015-02-04 21:48:00+00,402,19897,40.740343,517,Pershing Square South,40.751581,-73.977910,14691,Subscriber,1966.0,2
46144,NaN,Broadway & W 58 St,NaN,25241,-73.981693,9711,2015-02-05 11:12:00+00,2015-02-05 13:54:00+00,457,25203,40.766953,2021,W 45 St & 8 Ave,40.759291,-73.988597,14726,Subscriber,1962.0,1
46145,NaN,W 21 St & 6 Ave,NaN,15380,-73.994156,9807,2015-02-04 10:53:00+00,2015-02-04 13:36:00+00,435,15336,40.741740,435,W 21 St & 6 Ave,40.741740,-73.994156,18088,Subscriber,1985.0,1
46146,NaN,Broadway & W 55 St,NaN,9756,-73.981923,9938,2015-02-03 14:10:00+00,2015-02-03 16:55:00+00,468,9696,40.765265,2023,E 55 St & Lexington Ave,40.759681,-73.970314,19070,Subscriber,1970.0,1
46147,NaN,Centre St & Worth St,NaN,7538,-74.002345,9969,2015-02-02 18:22:00+00,2015-02-02 21:08:00+00,386,7472,40.714948,264,Maiden Ln & Pearl St,40.707065,-74.007319,19921,Subscriber,1987.0,2
46148,NaN,Washington St & Gansevoort St,NaN,40237,-74.008119,10174,2015-02-07 09:31:00+00,2015-02-07 12:20:00+00,405,40221,40.739323,405,Washington St & Gansevoort St,40.739323,-74.008119,21323,Subscriber,1983.0,1
46149,NaN,W 29 St & 9 Ave,NaN,10975,-73.998393,10660,2015-02-03 17:42:00+00,2015-02-03 20:40:00+00,512,10912,40.750073,435,W 21 St & 6 Ave,40.741740,-73.994156,16099,Subscriber,1950.0,1
46150,NaN,Greenwich Ave & 8 Ave,NaN,41403,-74.002638,10757,2015-02-07 12:17:00+00,2015-02-07 15:16:00+00,284,41392,40.739017,173,Broadway & W 49 St,40.760647,-73.984427,15082,Subscriber,1973.0,1

In [130]:
# Only show the top/last 10 records (aka head and tail in SQL)
# top
question1_2_1 = '''
SELECT *
FROM citibike
where tripduration <= 10800
order by tripduration ASC, start_station_id ASC
limit 10
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_2_1)), sep=',')

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,Laight St & Hudson St,NaN,19295,-74.007718,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,19243,40.721854,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970,1
1,NaN,Mott St & Prince St,NaN,8347,-73.994800,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,8284,40.723180,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982,1
2,NaN,Division St & Bowery,NaN,14163,-73.997047,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,14117,40.714131,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990,1
3,NaN,E 6 St & Avenue B,NaN,3178,-73.981854,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,3110,40.724537,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985,1
4,NaN,W 31 St & 7 Ave,NaN,7865,-73.991600,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,7798,40.749156,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986,1
5,NaN,E 5 St & Avenue C,NaN,45697,-73.979955,60,2015-02-07 21:40:00+00,2015-02-07 21:41:00+00,393,45697,40.722992,393,E 5 St & Avenue C,40.722992,-73.979955,21524,Subscriber,1981,1
6,NaN,E 10 St & Avenue A,NaN,38868,-73.981420,60,2015-02-06 20:40:00+00,2015-02-06 20:41:00+00,445,38842,40.727408,445,E 10 St & Avenue A,40.727408,-73.981420,16051,Subscriber,1987,1
7,NaN,W 20 St & 8 Ave,NaN,33793,-74.000040,60,2015-02-06 11:38:00+00,2015-02-06 11:39:00+00,470,33759,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,17448,Subscriber,1979,1
8,NaN,Grand St & Havemeyer St,NaN,11165,-73.956981,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,11104,40.712868,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980,1
9,NaN,5 Ave & E 29 St,NaN,7364,-73.986831,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,7299,40.745168,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956,1

In [131]:
# Only show the top/last 10 records (aka head and tail in SQL)

# last
question1_2_2 = '''
SELECT *
FROM citibike
where tripduration <= 10800
order by  start_station_id DESC, tripduration DESC
limit 10
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_2_2)), sep=',')

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,South End Ave & Liberty St,NaN,1576,-74.015756,7225,2015-02-01 11:46:00+00,2015-02-01 13:47:00+00,3002,1506,40.711512,499,Broadway & W 60 St,40.769155,-73.981918,21202,Customer,NaN,0
1,NaN,South End Ave & Liberty St,NaN,8891,-74.015756,2139,2015-02-03 09:33:00+00,2015-02-03 10:09:00+00,3002,8831,40.711512,510,W 51 St & 6 Ave,40.760660,-73.980420,15552,Subscriber,1958.0,1
2,NaN,South End Ave & Liberty St,NaN,23568,-74.015756,2131,2015-02-05 08:42:00+00,2015-02-05 09:17:00+00,3002,23529,40.711512,359,E 47 St & Park Ave,40.755103,-73.974987,21473,Subscriber,1985.0,1
3,NaN,South End Ave & Liberty St,NaN,10232,-74.015756,1977,2015-02-03 16:04:00+00,2015-02-03 16:37:00+00,3002,10173,40.711512,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,15309,Subscriber,1969.0,1
4,NaN,South End Ave & Liberty St,NaN,27243,-74.015756,1977,2015-02-05 16:11:00+00,2015-02-05 16:44:00+00,3002,27203,40.711512,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20069,Subscriber,1969.0,1
5,NaN,South End Ave & Liberty St,NaN,6846,-74.015756,1976,2015-02-02 09:21:00+00,2015-02-02 09:53:00+00,3002,6781,40.711512,494,W 26 St & 8 Ave,40.747348,-73.997236,19665,Subscriber,1959.0,1
6,NaN,South End Ave & Liberty St,NaN,44708,-74.015756,1920,2015-02-07 18:36:00+00,2015-02-07 19:08:00+00,3002,44703,40.711512,410,Suffolk St & Stanton St,40.720664,-73.985180,15443,Subscriber,1964.0,2
7,NaN,South End Ave & Liberty St,NaN,11648,-74.015756,1908,2015-02-03 18:54:00+00,2015-02-03 19:26:00+00,3002,11587,40.711512,279,Peck Slip & Front St,40.707873,-74.001670,19133,Subscriber,1996.0,1
8,NaN,South End Ave & Liberty St,NaN,1297,-74.015756,1900,2015-02-01 11:14:00+00,2015-02-01 11:45:00+00,3002,1228,40.711512,525,W 34 St & 11 Ave,40.755942,-74.002116,17849,Customer,NaN,0
9,NaN,South End Ave & Liberty St,NaN,17637,-74.015756,1830,2015-02-04 16:33:00+00,2015-02-04 17:04:00+00,3002,17590,40.711512,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20246,Subscriber,1969.0,1

In [120]:
# • List all unique start_station_id values
question1_3 = '''
SELECT distinct start_station_id
FROM citibike

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_3)), sep=',')

     start_station_id  Unnamed: 1
0                 120         NaN
1                 285         NaN
2                 251         NaN
3                 195         NaN
4                 453         NaN
5                 144         NaN
6                 266         NaN
7                 263         NaN
8                 216         NaN
9                 328         NaN
10                353         NaN
11                212         NaN
12                383         NaN
13                538         NaN
14                217         NaN
15                300         NaN
16                456         NaN
17                128         NaN
18                223         NaN
19                244         NaN
20                494         NaN
21                403         NaN
22                260         NaN
23                445         NaN
24                411         NaN
25                377         NaN
26                427         NaN
27                232         NaN
28                331         NaN
29                416         NaN
..                ...         ...
297               127         NaN
298               397         NaN
299               310         NaN
300               454         NaN
301               531         NaN
302               268         NaN
303               329         NaN
304               518         NaN
305               514         NaN
306               437         NaN
307               270         NaN
308               356         NaN
309               399         NaN
310               119         NaN
311               384         NaN
312               151         NaN
313               362         NaN
314               262         NaN
315               313         NaN
316              2008         NaN
317               276         NaN
318               470         NaN
319               455         NaN
320               496         NaN
321               312         NaN
322               318         NaN
323               497         NaN
324               305         NaN
325               264         NaN
326               483         NaN

[327 rows x 2 columns]

In [121]:
data.shape

(46200, 19)

In [125]:
# • Aggregation functions:
# - Count the number of trips (aka wc -l in SQL)
# - Find the average/min/max trip duration
question1_4_1 = '''
SELECT count(tripduration)
FROM citibike

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_4_1)), sep=',')

   count  Unnamed: 1
0  46200         NaN

In [126]:
# • Aggregation functions:
# - Find the average/min/max trip duration

question1_4_min = '''
SELECT min(tripduration) as min_trip_duration
FROM citibike

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_4_min)), sep=',')

   min_trip_duration  Unnamed: 1
0                 60         NaN

In [127]:
question1_4_max = '''
SELECT max(tripduration) as min_trip_duration
FROM citibike

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_4_max)), sep=',')

   min_trip_duration  Unnamed: 1
0              43016         NaN

In [128]:
question1_4_avg = '''
SELECT avg(tripduration) as min_trip_duration
FROM citibike

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question1_4_avg)), sep=',')

   min_trip_duration  Unnamed: 1
0         675.865823         NaN

### Task 2 — Working with date/time
###### Selecting trips started on Feb-02-2015 only
###### Selecting trips started on the weekends
###### What are average trip duration during weekends?
###### Can we do the same for weekday?

In [68]:
# Selecting trips started on Feb-02-2015 only
question2_1 = '''
select * from citibike 
where date(starttime) = '2015-02-02'

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question2_1)), sep=',')

# SELECT DATENAME(weekday, GETDATE())

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
1,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
2,NaN,E 5 St & Avenue C,NaN,11,-73.979955,1312,2015-02-02 11:07:00+00,2015-02-02 11:29:00+00,393,6920,40.722992,476,E 31 St & 3 Ave,40.743943,-73.979661,17720,Subscriber,1955.0,1
3,NaN,9 Ave & W 16 St,NaN,627,-74.004432,444,2015-02-02 00:40:00+00,2015-02-02 00:48:00+00,463,6477,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20233,Subscriber,1971.0,1
4,NaN,9 Ave & W 16 St,NaN,991,-74.004432,438,2015-02-02 00:40:00+00,2015-02-02 00:47:00+00,463,6478,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20264,Subscriber,1981.0,2
5,NaN,W 33 St & 7 Ave,NaN,1037,-73.990931,498,2015-02-02 06:20:00+00,2015-02-02 06:28:00+00,492,6526,40.750200,493,W 45 St & 6 Ave,40.756800,-73.982912,16013,Subscriber,1962.0,2
6,NaN,W 27 St & 7 Ave,NaN,6510,-73.993915,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,6442,40.746647,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
7,NaN,E 11 St & 1 Ave,NaN,6511,-73.984267,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,6443,40.729538,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
8,NaN,Peck Slip & Front St,NaN,6512,-74.001670,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,6444,40.707873,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
9,NaN,E 16 St & 5 Ave,NaN,6513,-73.992390,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,6445,40.737262,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
10,NaN,W 41 St & 8 Ave,NaN,6514,-73.990026,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,6446,40.756405,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
11,NaN,Dean St & 4 Ave,NaN,6515,-73.978951,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,6447,40.683125,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
12,NaN,9 Ave & W 18 St,NaN,6516,-74.003664,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,6448,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
13,NaN,Reade St & Broadway,NaN,6517,-74.005628,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,6449,40.714505,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
14,NaN,8 Ave & W 31 St,NaN,6518,-73.994811,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,6450,40.750450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
15,NaN,1 Ave & E 15 St,NaN,6519,-73.981656,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,6451,40.732219,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
16,NaN,Broadway & E 14 St,NaN,6520,-73.990741,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,6452,40.734546,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
17,NaN,E 2 St & Avenue B,NaN,6521,-73.983688,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,6453,40.722174,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
18,NaN,Peck Slip & Front St,NaN,6522,-74.001670,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,6454,40.707873,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
19,NaN,Columbia St & Rivington St,NaN,6523,-73.980166,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,6455,40.717400,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
20,NaN,W 20 St & 8 Ave,NaN,6524,-74.000040,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,6456,40.743453,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
21,NaN,St Marks Pl & 2 Ave,NaN,6525,-73.987140,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,6457,40.728419,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
22,NaN,W 20 St & 8 Ave,NaN,6526,-74.000040,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,6458,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
23,NaN,W 37 St & 5 Ave,NaN,6527,-73.983390,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,6459,40.750380,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
24,NaN,W 13 St & 6 Ave,NaN,6528,-73.997044,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,6460,40.736494,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
25,NaN,10 Ave & W 28 St,NaN,6529,-74.001768,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,6461,40.750664,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
26,NaN,E 25 St & 2 Ave,NaN,6530,-73.979738,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,6462,40.739126,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
27,NaN,W 4 St & 7 Ave S,NaN,6531,-74.002939,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,6463,40.734011,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
28,NaN,W 20 St & 7 Ave,NaN,6532,-73.997262,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,6464,40.742388,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
29,NaN,W 46 St & 11 Ave,NaN,6533,-73.996674,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,6465,40.763414,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,NaN,Allen St & E Houston St,NaN,7938,-73.989111,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,7871,40.722055,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,NaN,Broadway & W 29 St,NaN,7939,-73.988557,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,7872,40.746201,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,NaN,W 56 St & 6 Ave,NaN,7940,-73.977225,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,7873,40.763406,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,NaN,10 Ave & W 28 St,NaN,7941,-74.001768,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,7874,40.750664,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,NaN,W 26 St & 8 Ave,NaN,7942,-73.997236,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,7875,40.747348,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,NaN,Broadway & E 22 St,NaN,7943,-73.989551,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,7876,40.740343,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,NaN,E 47 St & 2 Ave,NaN,7944,-73.970325,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,7877,40.753231,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,NaN,Broadway & W 32 St,NaN,7945,-73.988084,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,7878,40.748549,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,NaN,8 Ave & W 31 St,NaN,7946,-73.994811,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,7879,40.750450,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,NaN,9 Ave & W 18 St,NaN,7947,-74.003664,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,7880,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,NaN,LaGuardia Pl & W 3 St,NaN,7948,-73.998102,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,7881,40.729170,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,NaN,W 26 St & 8 Ave,NaN,7949,-73.997236,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,7882,40.747348,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,NaN,Cliff St & Fulton St,NaN,7950,-74.005301,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,7883,40.708235,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,NaN,Rivington St & Ridge St,NaN,7951,-73.983299,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,7884,40.718502,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,NaN,W 49 St & 8 Ave,NaN,7952,-73.987882,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,7885,40.762272,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,NaN,Pershing Square North,NaN,7953,-73.977706,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,7886,40.751873,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,NaN,E 30 St & Park Ave S,NaN,7954,-73.983035,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,7887,40.744449,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,NaN,Sullivan St & Washington Sq,NaN,7955,-73.999061,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,7888,40.730477,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,NaN,W 42 St & 8 Ave,NaN,7956,-73.990985,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,7889,40.757570,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,NaN,Broadway & E 22 St,NaN,7957,-73.989551,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,7890,40.740343,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,NaN,1 Ave & E 15 St,NaN,7958,-73.981656,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,7891,40.732219,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,NaN,6 Ave & W 33 St,NaN,7959,-73.988484,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,7892,40.749013,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,NaN,9 Ave & W 22 St,NaN,7960,-74.001971,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,7893,40.745497,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,NaN,E 16 St & 5 Ave,NaN,7961,-73.992390,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,7894,40.737262,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,NaN,E 10 St & 5 Ave,NaN,7962,-73.995101,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,7895,40.733320,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,NaN,W 44 St & 5 Ave,NaN,7963,-73.980144,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,7896,40.755003,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,NaN,Spruce St & Nassau St,NaN,7964,-74.005524,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,7897,40.711464,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,NaN,W 13 St & 6 Ave,NaN,7965,-73.997044,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,7898,40.736494,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,NaN,W 22 St & 8 Ave,NaN,7966,-73.999154,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,7899,40.744751,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,NaN,Broadway & E 14 St,NaN,7967,-73.990741,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,7900,40.734546,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

In [133]:
# Selecting trips started on the weekend
question2_2 = '''
select *
From citibike
where extract(dow from starttime) in(0,6)
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question2_2)), sep=',')

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1
2,NaN,E 6 St & Avenue B,NaN,2827,-73.981854,751,2015-02-01 13:59:00+00,2015-02-01 14:11:00+00,317,2759,40.724537,466,W 25 St & 6 Ave,40.743954,-73.991449,14788,Subscriber,1990.0,1
3,NaN,E 12 St & 3 Ave,NaN,4961,-73.988900,272,2015-02-01 17:28:00+00,2015-02-01 17:32:00+00,483,4893,40.732233,345,W 13 St & 6 Ave,40.736494,-73.997044,16219,Subscriber,1961.0,1
4,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
5,NaN,E 20 St & 2 Ave,NaN,39894,-73.982050,296,2015-02-07 08:13:00+00,2015-02-07 08:18:00+00,461,39876,40.735877,435,W 21 St & 6 Ave,40.741740,-73.994156,17278,Subscriber,1987.0,1
6,NaN,Broadway & W 60 St,NaN,41512,-73.981918,600,2015-02-07 12:35:00+00,2015-02-07 12:45:00+00,499,41501,40.769155,523,W 38 St & 8 Ave,40.754666,-73.991382,15224,Subscriber,1959.0,1
7,NaN,E 6 St & Avenue D,NaN,41595,-73.976687,1203,2015-02-07 12:47:00+00,2015-02-07 13:07:00+00,411,41585,40.722281,428,E 3 St & 1 Ave,40.724677,-73.987834,21461,Subscriber,1968.0,1
8,NaN,Great Jones St,NaN,41806,-73.993790,520,2015-02-07 13:16:00+00,2015-02-07 13:25:00+00,229,41796,40.727434,168,W 18 St & 6 Ave,40.739713,-73.994564,14621,Subscriber,1964.0,1
9,NaN,W 13 St & 6 Ave,NaN,42316,-73.997044,487,2015-02-07 14:18:00+00,2015-02-07 14:26:00+00,345,42307,40.736494,509,9 Ave & W 22 St,40.745497,-74.001971,21362,Subscriber,1962.0,1
10,NaN,W 34 St & 11 Ave,NaN,42532,-74.002116,984,2015-02-07 14:42:00+00,2015-02-07 14:59:00+00,525,42523,40.755942,388,W 26 St & 10 Ave,40.749718,-74.002950,14549,Customer,NaN,0
11,NaN,W 41 St & 8 Ave,NaN,42915,-73.990026,621,2015-02-07 15:23:00+00,2015-02-07 15:33:00+00,477,42906,40.756405,509,9 Ave & W 22 St,40.745497,-74.001971,20216,Subscriber,1980.0,1
12,NaN,E 25 St & 1 Ave,NaN,44448,-73.977387,397,2015-02-07 18:03:00+00,2015-02-07 18:10:00+00,174,44443,40.738177,528,2 Ave & E 31 St,40.742909,-73.977061,15948,Subscriber,1991.0,1
13,NaN,E 15 St & 3 Ave,NaN,44744,-73.986923,352,2015-02-07 18:39:00+00,2015-02-07 18:45:00+00,297,44739,40.734232,507,E 25 St & 2 Ave,40.739126,-73.979738,15367,Subscriber,1978.0,1
14,NaN,W 33 St & 7 Ave,NaN,44834,-73.990931,1063,2015-02-07 18:53:00+00,2015-02-07 19:11:00+00,492,44829,40.750200,174,E 25 St & 1 Ave,40.738177,-73.977387,20702,Subscriber,1989.0,2
15,NaN,E 33 St & 2 Ave,NaN,45301,-73.976056,483,2015-02-07 19:59:00+00,2015-02-07 20:07:00+00,527,45297,40.744023,325,E 19 St & 3 Ave,40.736245,-73.984738,20296,Subscriber,1984.0,1
16,NaN,8 Ave & W 33 St,NaN,0,-73.993934,447,2015-02-01 01:11:00+00,2015-02-01 01:19:00+00,490,93,40.751551,479,9 Ave & W 45 St,40.760193,-73.991255,15185,Subscriber,1983.0,2
17,NaN,Broadway & W 39 St,NaN,1,-73.987216,277,2015-02-01 10:26:00+00,2015-02-01 10:30:00+00,533,847,40.752996,515,W 43 St & 10 Ave,40.760094,-73.994618,16452,Subscriber,1978.0,1
18,NaN,W 18 St & 6 Ave,NaN,2,-73.994564,526,2015-02-01 11:07:00+00,2015-02-01 11:16:00+00,168,1180,40.739713,521,8 Ave & W 31 St,40.750450,-73.994811,16741,Subscriber,1984.0,1
19,NaN,Broadway & E 22 St,NaN,3,-73.989551,502,2015-02-01 12:37:00+00,2015-02-01 12:46:00+00,402,1971,40.740343,459,W 20 St & 11 Ave,40.746745,-74.007756,16951,Subscriber,1983.0,1
20,NaN,W 46 St & 11 Ave,NaN,4,-73.996674,943,2015-02-01 12:46:00+00,2015-02-01 13:02:00+00,508,2053,40.763414,521,8 Ave & W 31 St,40.750450,-73.994811,16897,Subscriber,1966.0,2
21,NaN,Great Jones St,NaN,5,-73.993790,563,2015-02-01 12:54:00+00,2015-02-01 13:03:00+00,229,2138,40.727434,346,Bank St & Hudson St,40.736529,-74.006180,16722,Subscriber,1984.0,1
22,NaN,Carmine St & 6 Ave,NaN,6,-74.002150,519,2015-02-01 15:21:00+00,2015-02-01 15:29:00+00,368,3591,40.730386,503,E 20 St & Park Ave,40.738274,-73.987520,15196,Subscriber,1968.0,1
23,NaN,E 12 St & 3 Ave,NaN,7,-73.988900,500,2015-02-01 17:38:00+00,2015-02-01 17:47:00+00,483,4983,40.732233,435,W 21 St & 6 Ave,40.741740,-73.994156,19409,Customer,NaN,0
24,NaN,W 20 St & 7 Ave,NaN,8,-73.997262,374,2015-02-01 17:48:00+00,2015-02-01 17:55:00+00,334,5067,40.742388,497,E 17 St & Broadway,40.737050,-73.990093,21456,Customer,NaN,0
25,NaN,E 11 St & 1 Ave,NaN,9,-73.984267,420,2015-02-01 19:26:00+00,2015-02-01 19:33:00+00,326,5748,40.729538,527,E 33 St & 2 Ave,40.744023,-73.976056,14878,Subscriber,1988.0,1
26,NaN,W 24 St & 7 Ave,NaN,10,-73.995299,315,2015-02-01 21:34:00+00,2015-02-01 21:39:00+00,446,6086,40.744876,521,8 Ave & W 31 St,40.750450,-73.994811,16042,Subscriber,1956.0,1
27,NaN,W 33 St & 7 Ave,NaN,38,-73.990931,302,2015-02-07 06:33:00+00,2015-02-07 06:38:00+00,492,39722,40.750200,493,W 45 St & 6 Ave,40.756800,-73.982912,18472,Subscriber,1972.0,1
28,NaN,W 17 St & 8 Ave,NaN,49,-74.001497,424,2015-02-07 00:00:00+00,2015-02-07 00:07:00+00,116,39412,40.741776,489,10 Ave & W 28 St,40.750664,-74.001768,19071,Subscriber,1963.0,1
29,NaN,E 15 St & 3 Ave,NaN,50,-73.986923,439,2015-02-07 03:43:00+00,2015-02-07 03:50:00+00,297,39651,40.734232,527,E 33 St & 2 Ave,40.744023,-73.976056,21448,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13201,NaN,Washington Pl & Broadway,NaN,46170,-73.994046,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,46171,40.729039,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
13202,NaN,Allen St & Hester St,NaN,46171,-73.991908,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,46172,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
13203,NaN,Warren St & Church St,NaN,46172,-74.009106,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,46173,40.714740,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
13204,NaN,E 12 St & 3 Ave,NaN,46173,-73.988900,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,46174,40.732233,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
13205,NaN,Dean St & 4 Ave,NaN,46174,-73.978951,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,46175,40.683125,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
13206,NaN,Allen St & Hester St,NaN,46175,-73.991908,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,46176,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
13207,NaN,Broadway & E 22 St,NaN,46176,-73.989551,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,46177,40.740343,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
13208,NaN,Washington Pl & 6 Ave,NaN,46177,-74.000264,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,46178,40.732241,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
13209,NaN,E 31 St & 3 Ave,NaN,46178,-73.979661,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,46179,40.743943,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
13210,NaN,Broadway & W 60 St,NaN,46179,-73.981918,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,46180,40.769155,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
13211,NaN,Carmine St & 6 Ave,NaN,46180,-74.002150,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,46181,40.730386,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
13212,NaN,W 52 St & 5 Ave,NaN,46181,-73.976485,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,46182,40.759923,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
13213,NaN,Dean St & 4 Ave,NaN,46182,-73.978951,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,46183,40.683125,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
13214,NaN,9 Ave & W 45 St,NaN,46183,-73.991255,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,46184,40.760193,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
13215,NaN,Broadway & W 58 St,NaN,46184,-73.981693,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46185,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
13216,NaN,Broadway & W 58 St,NaN,46185,-73.981693,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46186,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
13217,NaN,Watts St & Greenwich St,NaN,46186,-74.009660,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,46187,40.724055,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
13218,NaN,W 51 St & 6 Ave,NaN,46187,-73.980420,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,46188,40.760660,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
13219,NaN,University Pl & E 14 St,NaN,46188,-73.992005,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,46189,40.734927,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
13220,NaN,W 11 St & 6 Ave,NaN,46189,-73.998004,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,46190,40.735324,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
13221,NaN,W 17 St & 8 Ave,NaN,46190,-74.001497,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,46191,40.741776,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
13222,NaN,W 47 St & 10 Ave,NaN,46191,-73.993012,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,46192,40.762699,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
13223,NaN,Warren St & Church St,NaN,46192,-74.009106,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,46193,40.714740,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
13224,NaN,E 20 St & 2 Ave,NaN,46193,-73.982050,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,46194,40.735877,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
13225,NaN,1 Ave & E 44 St,NaN,46194,-73.969053,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,46195,40.750020,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
13226,NaN,W 20 St & 8 Ave,NaN,46195,-74.000040,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,46196,40.743453,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
13227,NaN,5 Ave & E 29 St,NaN,46196,-73.986831,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,46197,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
13228,NaN,5 Ave & E 29 St,NaN,46197,-73.986831,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,46198,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
13229,NaN,Carmine St & 6 Ave,NaN,46198,-74.002150,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,46199,40.730386,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
13230,NaN,E 4 St & 2 Ave,NaN,46199,-73.989780,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,46200,40.726281,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

In [134]:
# average trip duration started on the weekend
question2_3 = '''
select avg(tripduration)
From citibike
where extract(dow from starttime) in(0,6)
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question2_3)), sep=',')

          avg  Unnamed: 1
0  662.942181         NaN

In [136]:
#What are average trip duration during weekday
question2_4 = '''
select avg(tripduration)
From citibike
where extract(dow from starttime) not in (0,6)
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question2_4)), sep=',')

          avg  Unnamed: 1
0  681.052292         NaN

### Task 3 — Working with Space
###### Showing the list of start station locations
###### Using GROUP BY
###### Showing the number of trips started per station
###### but only for stations within 500m of Time Square!
###### The coordinates of Time Square is (40.7577,-73.9857)

In [139]:
# Showing the list of start station locations
question3_1 = '''
select start_station_id,start_station_longitude, start_station_latitude
from citibike'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question3_1)), sep=',')

       start_station_id  start_station_longitude  start_station_latitude
0                   503               -73.987520               40.738274
1                   515               -73.994618               40.760094
2                   317               -73.981854               40.724537
3                   483               -73.988900               40.732233
4                   477               -73.990026               40.756405
5                   474               -73.986831               40.745168
6                   361               -73.991908               40.716059
7                   167               -73.976049               40.748901
8                   489               -74.001768               40.750664
9                   403               -73.990697               40.725029
10                  455               -73.969053               40.750020
11                  493               -73.982912               40.756800
12                  168               -73.994564               40.739713
13                  305               -73.967245               40.760958
14                  526               -73.984907               40.747659
15                  379               -73.991600               40.749156
16                  474               -73.986831               40.745168
17                  518               -73.973442               40.747804
18                  489               -74.001768               40.750664
19                  529               -73.990985               40.757570
20                 2012               -73.976806               40.739445
21                  229               -73.993790               40.727434
22                  450               -73.987882               40.762272
23                  444               -73.989151               40.742354
24                  153               -73.981632               40.752062
25                  496               -73.992390               40.737262
26                  267               -73.987654               40.750977
27                  521               -73.994811               40.750450
28                  493               -73.982912               40.756800
29                  501               -73.971212               40.744219
...                 ...                      ...                     ...
46170               335               -73.994046               40.729039
46171               361               -73.991908               40.716059
46172               152               -74.009106               40.714740
46173               483               -73.988900               40.732233
46174               467               -73.978951               40.683125
46175               361               -73.991908               40.716059
46176               402               -73.989551               40.740343
46177               369               -74.000264               40.732241
46178               476               -73.979661               40.743943
46179               499               -73.981918               40.769155
46180               368               -74.002150               40.730386
46181               520               -73.976485               40.759923
46182               467               -73.978951               40.683125
46183               479               -73.991255               40.760193
46184               457               -73.981693               40.766953
46185               457               -73.981693               40.766953
46186               328               -74.009660               40.724055
46187               510               -73.980420               40.760660
46188               382               -73.992005               40.734927
46189               254               -73.998004               40.735324
46190               116               -74.001497               40.741776
46191               495               -73.993012               40.762699
46192               152               -74.009106               40.714740
46193               461               -73.982050               40.735877
46194               455               -73.969053               40.750020
46195               470               -74.000040               40.743453
46196               474               -73.986831               40.745168
46197               474               -73.986831               40.745168
46198               368               -74.002150               40.730386
46199               439               -73.989780               40.726281

[46200 rows x 3 columns]

In [158]:
# Showing the number of trips started per station
question3_2 = '''
select count(tripduration),start_station_id
from citibike
group by start_station_id
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question3_2)), sep=',')

     count  start_station_id
0       17               120
1      373               285
2      194               251
3      137               195
4      218               453
5        7               144
6       38               266
7      217               263
8       12               216
9       73               328
10      29               353
11     186               212
12     142               383
13     153               538
14      14               217
15     161               300
16     110               456
17     247               128
18     179               223
19      35               244
20     237               494
21     151               403
22      36               260
23     296               445
24      86               411
25     101               377
26      42               427
27      22               232
28      52               331
29      36               416
..     ...               ...
297    209               127
298     27               397
299     62               310
300     55               454
301    212               531
302    124               268
303    145               329
304    282               518
305     91               514
306     18               437
307     92               270
308     98               356
309     32               399
310     19               119
311     55               384
312    288               151
313     98               362
314     37               262
315     50               313
316     86              2008
317     65               276
318    173               470
319    110               455
320    250               496
321    207               312
322    486               318
323    455               497
324    213               305
325    115               264
326    229               483

[327 rows x 2 columns]

In [149]:
# for stations within 500m of Time Square!
# The coordinates of Time Square is (40.7577,-73.9857)
question3_3 = '''
select count(tripduration),start_station_id
from citibike
where st_dwithin(
CDB_LatLng(start_station_latitude, start_station_longitude)::geography, CDB_LatLng(40.7577, -73.9857)::geography, 500)
Group by start_station_id
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question3_3)), sep=',')

   count  start_station_id
0    213               173
1    251               465
2    507               477
3    141               493
4    112               524
5    221               529
6    141              2021

### Task 4 — Putting it all together
###### Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare
###### Extra create lines for trips started from stations within 500m of Times
###### Squares and lasted less than 2 hours. The number of trips per each pair of stations are output as attributes of these lines.

In [160]:
#Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare
question4_1 = '''
select AVG(tripduration)as duration,start_station_name
from citibike
where st_dwithin(
CDB_LatLng(start_station_latitude, start_station_longitude)::geography, CDB_LatLng(40.7577, -73.9857)::geography, 500)
and EXTRACT(dow from starttime) in (0,6)
Group by start_station_name
Order by duration DESC
Limit 1
'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question4_1)), sep=',')

      duration  start_station_name
0  1010.104167  Broadway & W 49 St

In [170]:
# extra credit
question4_2='''
select count(start_station_id) as num_trips, start_station_name, end_station_name
from citibike
where st_dwithin(
CDB_LatLng(start_station_latitude, start_station_longitude)::geography, CDB_LatLng(40.7577, -73.9857)::geography, 500)
and tripduration <= 7200
Group by start_station_name, end_station_name

'''
pd.read_csv(StringIO.StringIO(queryCartoDB(question4_2)), sep=',')

     num_trips  start_station_name                   end_station_name
0            1  Broadway & W 41 St                   10 Ave & W 28 St
1           12  Broadway & W 41 St                   11 Ave & W 41 St
2            2  Broadway & W 41 St                   12 Ave & W 40 St
3            1  Broadway & W 41 St                    1 Ave & E 15 St
4            2  Broadway & W 41 St                    1 Ave & E 44 St
5            2  Broadway & W 41 St                    2 Ave & E 31 St
6            6  Broadway & W 41 St                    6 Ave & W 33 St
7            4  Broadway & W 41 St                    8 Ave & W 33 St
8            2  Broadway & W 41 St                    8 Ave & W 52 St
9            5  Broadway & W 41 St                    9 Ave & W 22 St
10           1  Broadway & W 41 St                    9 Ave & W 45 St
11           1  Broadway & W 41 St               Allen St & Hester St
12           1  Broadway & W 41 St            Allen St & Rivington St
13           2  Broadway & W 41 St                Bank St & Hudson St
14           2  Broadway & W 41 St                 Broadway & E 14 St
15           4  Broadway & W 41 St                 Broadway & E 22 St
16           5  Broadway & W 41 St                 Broadway & W 24 St
17           4  Broadway & W 41 St                 Broadway & W 29 St
18           2  Broadway & W 41 St                 Broadway & W 32 St
19           7  Broadway & W 41 St                 Broadway & W 36 St
20           5  Broadway & W 41 St                 Broadway & W 37 St
21           5  Broadway & W 41 St                 Broadway & W 39 St
22           3  Broadway & W 41 St                 Broadway & W 41 St
23           1  Broadway & W 41 St                 Broadway & W 49 St
24           1  Broadway & W 41 St                 Broadway & W 60 St
25           1  Broadway & W 41 St                          Cherry St
26           1  Broadway & W 41 St            Duane St & Greenwich St
27           1  Broadway & W 41 St                    E 10 St & 5 Ave
28           4  Broadway & W 41 St                 E 10 St & Avenue A
29           2  Broadway & W 41 St                 E 14 St & Avenue B
..         ...                 ...                                ...
542          1     W 45 St & 8 Ave                    E 56 St & 3 Ave
543          2     W 45 St & 8 Ave              E 56 St & Madison Ave
544          1     W 45 St & 8 Ave                    E 58 St & 3 Ave
545          3     W 45 St & 8 Ave  Grand Army Plaza & Central Park S
546          1     W 45 St & 8 Ave            Lexington Ave & E 24 St
547          2     W 45 St & 8 Ave            Suffolk St & Stanton St
548          2     W 45 St & 8 Ave                    W 15 St & 7 Ave
549          3     W 45 St & 8 Ave                   W 20 St & 11 Ave
550          1     W 45 St & 8 Ave                    W 20 St & 7 Ave
551          3     W 45 St & 8 Ave                    W 20 St & 8 Ave
552          1     W 45 St & 8 Ave                    W 21 St & 6 Ave
553          1     W 45 St & 8 Ave                    W 22 St & 8 Ave
554          1     W 45 St & 8 Ave                    W 24 St & 7 Ave
555          3     W 45 St & 8 Ave                    W 29 St & 9 Ave
556          3     W 45 St & 8 Ave                    W 33 St & 7 Ave
557          1     W 45 St & 8 Ave                   W 34 St & 11 Ave
558          3     W 45 St & 8 Ave                    W 39 St & 9 Ave
559          1     W 45 St & 8 Ave                    W 42 St & 8 Ave
560          4     W 45 St & 8 Ave                   W 43 St & 10 Ave
561          7     W 45 St & 8 Ave                    W 45 St & 8 Ave
562          2     W 45 St & 8 Ave                   W 46 St & 11 Ave
563          4     W 45 St & 8 Ave                   W 47 St & 10 Ave
564          2     W 45 St & 8 Ave                    W 51 St & 6 Ave
565          1     W 45 St & 8 Ave                   W 52 St & 11 Ave
566          1     W 45 St & 8 Ave                    W 52 St & 5 Ave
567          1     W 45 St & 8 Ave                   W 53 St & 10 Ave
568          1     W 45 St & 8 Ave                   W 56 St & 10 Ave
569          2     W 45 St & 8 Ave                    W 56 St & 6 Ave
570          1     W 45 St & 8 Ave           Washington Pl & Broadway
571          2     W 45 St & 8 Ave            Watts St & Greenwich St

[572 rows x 3 columns]